### PR TITLE
update sentry version

### PR DESCRIPTION
**Pull request by tuliocll**

### CODE REVIEW

**Comment by mateus4k** [comment]
Please approve this PR, @Perafan18 😃

**Review by Perafan18 — APPROVED** [review]
:shipit:

**Comment by dguzman1012** [comment]
Hello @Perafan18. This PR was merged into the master branch. However the npm package is still using an [old version of sentry/node](https://github.com/Perafan18/adonis-sentry/blob/2.1.2/package.json#L30). Would you please make a release for the npm package as well? (We can use the master branch for now of course)


PS: The latest release of @sentry/node is the [6.3.1](https://github.com/getsentry/sentry-javascript/releases/tag/6.3.1)

**Comment by Perafan18** [comment]
@dguzman1012  @tuliocll  @mateus4k sorry for the delay, I already make the release. 
https://github.com/Perafan18/adonis-sentry/releases/tag/2.1.4

**Pull request merged**
